In [1]:
#Create a null vector of size 10 but the fifth value which is 1 

import numpy as np

vector = np.zeros(10)
vector[4] = 1
print(vector)



[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [2]:
#2. Create a vector with values ranging from 10 to 49

vector = np.arange(10, 50)
print(vector)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [3]:
#3. Reverse a vector
vector = np.arange(10, 50)
reversed_vector = np.flip(vector)
print(reversed_vector)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [4]:
#4. Create a 3x3 matrix with values ranging from 0 to 8

matrix = np.arange(0, 9).reshape(3, 3)
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [5]:
#5. Find indices of non-zero elements from [1,2,0,0,4,0]

vector = np.array([1, 2, 0, 0, 4, 0])
indices = np.nonzero(vector)
print(indices)

(array([0, 1, 4], dtype=int64),)


In [6]:
# 6. Create a 3x3x3 array with random values

array = np.random.rand(3, 3, 3)
print(array)

[[[0.4124343  0.98855068 0.16935815]
  [0.02069296 0.8555627  0.01327944]
  [0.01846512 0.74898363 0.46777021]]

 [[0.24884517 0.45646622 0.0753036 ]
  [0.41043697 0.26670873 0.92557822]
  [0.15057721 0.5595526  0.30335109]]

 [[0.73163125 0.10210916 0.87147511]
  [0.39879605 0.59542509 0.07358456]
  [0.62091873 0.67237371 0.76416202]]]


In [7]:
#7. Create a 10x10 array with random values and find the minimum and maximum values

array = np.random.rand(3, 3, 3)
print(array)

[[[0.80475415 0.96488927 0.67062684]
  [0.21915738 0.09220564 0.22365959]
  [0.77708503 0.99570573 0.74904832]]

 [[0.4132341  0.72259991 0.50276123]
  [0.3465722  0.37393033 0.78178435]
  [0.26542286 0.29204672 0.71509365]]

 [[0.20075186 0.75200932 0.72541933]
  [0.32617822 0.35651564 0.96486829]
  [0.83505523 0.37573189 0.29366112]]]


In [8]:
#8. Create a 2d array with 1 on the border and 0 inside
array = np.ones((10, 10))
array[1:-1, 1:-1] = 0
print(array)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
